### ISSUE TITLE
Exporting/Saving to VCF

### ISSUE THREAD

**Issue by bio-bench** [tkoomar/VCFdbR#3]
Is it possible to export all/filtered contents of the DB back into a VCF file for other downstream uses?

**Comment by tkoomar** [comment]
**There is no existing functionality to export data in a VCF format.** All of the needed information (including the header) are preserved in the database, so this is theoretically possible. However, the parsing  that occurs to get the VCF formatted data into an SQL friendly format would be computationally expensive to reverse. 

If you will frequently require VCF formatted data for downstream analyses, VCFdbR may not be the right tool for your needs (or, at least that particular use case). **I would suggest bcftools** for doing this, as it is computationally efficient and designed for VCF/BCF input and output: 
http://samtools.github.io/bcftools/bcftools.html#filter
http://samtools.github.io/bcftools/bcftools.html#expressions
http://samtools.github.io/bcftools/howtos/filtering.html

**Comment by bio-bench** [comment]
Thanks Tanner! Appreciate your help. I am trying to merge two VCF files ( one large and one small) but in a repetitive fashion. My first resort was bcftools but merging these two files takes a long time (in hours). I thought if there was a way to append the small VCFs to a db table, then exporting the merged VCF would become easy. 

In any case I will start exploring other tools. Thanks for your inputs :)
