### ISSUE TITLE
 Getting 'seqnames' in 'vcfWhich(param)' must be present in 'genome'

### ISSUE THREAD

**Issue by stefanrybacki** [tkoomar/VCFdbR#5]
I am getting, in the stage `CHECKING GENOTYPE FIELDS`:

```
Error in .readVcf(file, genome, param, row.names = row.names, ...) :
  'seqnames' in 'vcfWhich(param)' must be present in 'genome'
Calls: source ... eval -> eval -> readVcf -> readVcf -> .local -> .readVcf
```

Do you have any idea what and where to look for in the VCF?

Thanks in advance

**Comment by tkoomar** [comment]
What does the header of your VCF look like? This suggests that there is record in the VCF for a chromosome which is not declared in the header, or that there are no chromosomes declared in the header at all.
